// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./src/components/hello.vue')['default']
    TestComponent: typeof import('./src/components/testComponent/index.vue')['default']
  }
}

export { }
